project:
  type: website

website:
  title: "A Walk on the Wild Side"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: vapor
    css: styles.css
execute: 
  freeze: auto


